import { describe, it, expect, beforeEach } from 'vitest';
import {
  ENVELOPE_VERSION,
  ENCRYPTED_EVENTS,
  CHECKIN_PAD,
  PAD_LADDER,
  SLIDES_PAD_LADDER,
  paddedSize,
  fromBase64,
  toBase64,
  isPlausibleKey,
  importDisplayKey,
  isEnvelope,
  openEnvelope,
  sealForTest,
  _resetKeyCache,
} from './envelope.js';
import fixture from './__fixtures__/envelope-vectors.json';

// THE INTEROP TEST IS THE POINT OF THIS FILE.
//
// The seal lives in the printer repo (print-server/events.js, Node crypto) and
// the open lives here (WebCrypto). Two independent implementations of one wire
// format is exactly the situation where both sides pass their own tests and no
// child's name ever reaches a screen. So both are pinned to ONE committed
// artifact: envelope-vectors.json, generated by the printer and mirrored here
// byte-identically. The printer asserts it can still open every envelope in it;
// so does this file. A framing change on either side breaks that side's build
// instead of the club night.
//
// The other block that carries real weight is "forged frames": encryption-shaped
// code that accepts a tampered frame, or hands back partial plaintext when the
// tag check fails, is worse than no encryption — it carries the confidence
// without the property.

const keyBytes = () => fromBase64(fixture.testKey);

beforeEach(() => { _resetKeyCache(); });

describe('the framing this build implements matches the fixture', () => {
  it('agrees with the printer on version, pad and ladders', () => {
    expect(fixture.envelopeVersion).toBe(ENVELOPE_VERSION);
    expect(fixture.checkinPad).toBe(CHECKIN_PAD);
    expect(fixture.padLadder).toEqual(PAD_LADDER);
    expect(fixture.slidesPadLadder).toEqual(SLIDES_PAD_LADDER);
    expect(fixture.encryptedEvents).toEqual(ENCRYPTED_EVENTS);
  });

  it('slides pads fail closed above their top rung — the 8192 rung must not exist for them', () => {
    // (paddedSize takes the JSON length; the rung includes the 4-byte prefix)
    expect(paddedSize('slides', 2000)).toBe(2048);
    expect(paddedSize('slides', 2044)).toBe(2048);
    expect(paddedSize('slides', 2045)).toBe(4096);
    expect(paddedSize('slides', 4092)).toBe(4096);
    expect(paddedSize('slides', 4093)).toBeNull();
    expect(paddedSize('slides', 50000)).toBeNull();
  });
});

describe('interop: envelopes sealed by the Node publisher open here', () => {
  it('has cases for every encrypted event', () => {
    const events = new Set(fixture.cases.map((c) => c.event));
    for (const e of ENCRYPTED_EVENTS) expect(events).toContain(e);
  });

  for (const c of fixture.cases) {
    it(`opens ${c.vector} to its exact payload`, async () => {
      const imported = await importDisplayKey(fixture.testKey);
      expect(imported).not.toBeNull();
      const result = await openEnvelope(imported, c.event, c.envelope);
      expect(result.ok).toBe(true);
      // Deep equality, not shape: a framing bug that dropped or reordered a
      // field would otherwise pass.
      expect(result.payload).toEqual(c.payload);
    });
  }

  it('agrees with the publisher on the kid fingerprint', async () => {
    const imported = await importDisplayKey(fixture.testKey);
    for (const c of fixture.cases) expect(c.envelope.kid).toBe(imported.kid);
  });
});

describe('forged, tampered and replayed frames are rejected', () => {
  /** A freshly sealed checkin to attack. */
  async function sealed() {
    return sealForTest(keyBytes(), 'checkin', { firstName: 'Amy', club: 'Sparks', id: 'x', at: 'y' });
  }

  it('a wrong key fails authentication rather than returning garbage', async () => {
    const env = await sealed();
    const other = new Uint8Array(32).fill(7);
    const imported = await importDisplayKey(toBase64(other));
    const result = await openEnvelope(imported, 'checkin', env);
    expect(result.ok).toBe(false);
    // The kid check catches it first, which is the more useful message: it means
    // "someone rotated the key and this screen was not re-pasted".
    expect(result.reason).toBe('kid-mismatch');
  });

  it('a checkin ciphertext replayed under another event name fails on the AAD', async () => {
    const env = await sealed();
    const imported = await importDisplayKey(fixture.testKey);
    for (const wrongEvent of ['recap', 'birthdays', 'tally']) {
      const result = await openEnvelope(imported, wrongEvent, env);
      expect(result.ok).toBe(false);
      expect(result.reason).toBe('auth-failed');
    }
  });

  it('a single flipped ciphertext byte fails, with no partial plaintext', async () => {
    const env = await sealed();
    const ct = fromBase64(env.ct);
    ct[12] ^= 0x01;
    const imported = await importDisplayKey(fixture.testKey);
    const result = await openEnvelope(imported, 'checkin', { ...env, ct: toBase64(ct) });
    expect(result.ok).toBe(false);
    expect(result.reason).toBe('auth-failed');
    expect(result).not.toHaveProperty('payload');
  });

  it('a tampered auth tag fails', async () => {
    const env = await sealed();
    const ct = fromBase64(env.ct);
    ct[ct.length - 1] ^= 0x80;
    const imported = await importDisplayKey(fixture.testKey);
    expect((await openEnvelope(imported, 'checkin', { ...env, ct: toBase64(ct) })).ok).toBe(false);
  });

  it('a substituted IV fails', async () => {
    const env = await sealed();
    const iv = fromBase64(env.iv);
    iv[0] ^= 0xff;
    const imported = await importDisplayKey(fixture.testKey);
    expect((await openEnvelope(imported, 'checkin', { ...env, iv: toBase64(iv) })).ok).toBe(false);
  });

  it('a truncated ciphertext is rejected as malformed, not decrypted', async () => {
    const env = await sealed();
    const imported = await importDisplayKey(fixture.testKey);
    const short = toBase64(fromBase64(env.ct).subarray(0, 8));
    const result = await openEnvelope(imported, 'checkin', { ...env, ct: short });
    expect(result.ok).toBe(false);
    expect(result.reason).toBe('malformed');
  });

  it('reuses no IV across frames', async () => {
    const seen = new Set();
    for (let i = 0; i < 25; i++) seen.add((await sealed()).iv);
    // A repeated (key, IV) pair in GCM is catastrophic, not merely weak.
    expect(seen.size).toBe(25);
  });

  it('never throws, whatever it is handed', async () => {
    const imported = await importDisplayKey(fixture.testKey);
    const junk = [null, undefined, 0, '', 'string', [], {}, { v: 1 },
      { v: 2, kid: 'a', iv: 'b', ct: 'c' },
      { v: 1, kid: 1, iv: 2, ct: 3 },
      { v: 1, kid: 'aa', iv: '!!!!', ct: '!!!!' }];
    for (const j of junk) {
      const result = await openEnvelope(imported, 'checkin', j);
      expect(result.ok).toBe(false);
      expect(typeof result.reason).toBe('string');
    }
  });
});

describe('key handling', () => {
  it('reports no-key rather than crashing when this screen has none', async () => {
    const result = await openEnvelope(null, 'checkin', fixture.cases[0].envelope);
    expect(result).toEqual({ ok: false, reason: 'no-key' });
  });

  it('rejects keys that are not 32 bytes of base64', async () => {
    for (const bad of ['', '   ', 'not base64!!', toBase64(new Uint8Array(16)),
      toBase64(new Uint8Array(64)), null, undefined]) {
      expect(isPlausibleKey(bad)).toBe(false);
      expect(await importDisplayKey(bad)).toBeNull();
    }
    expect(isPlausibleKey(fixture.testKey)).toBe(true);
  });

  it('memoises the imported key so a busy night does not re-import per frame', async () => {
    const a = importDisplayKey(fixture.testKey);
    const b = importDisplayKey(fixture.testKey);
    expect(a).toBe(b);
    expect(await a).toBe(await b);
  });
});

describe('padding closes the length channel', () => {
  it('seals every checkin to an identical length, whatever the name', async () => {
    const lengths = new Set();
    for (const probe of [
      { firstName: 'A', club: 'X' },
      { firstName: 'Bartholomew', club: 'Truth & Training' },
      { firstName: 'A'.repeat(40), club: 'C'.repeat(40) },
    ]) {
      const env = await sealForTest(keyBytes(), 'checkin', { ...probe, id: 'i', at: 'a' });
      lengths.add(env.ct.length);
    }
    expect(lengths.size).toBe(1);
  });

  it('seals every checkin vector in the fixture to the same length', () => {
    const lengths = new Set(
      fixture.cases.filter((c) => c.event === 'checkin').map((c) => c.envelope.ct.length));
    expect(lengths.size).toBe(1);
  });

  it('refuses an oversized checkin rather than silently using a bigger rung', () => {
    // Falling back to a larger size would reintroduce the length channel for
    // exactly the frames that matter most, so this must be null (fail closed).
    expect(paddedSize('checkin', CHECKIN_PAD)).toBeNull();
    expect(paddedSize('checkin', 10)).toBe(CHECKIN_PAD);
  });

  it('puts bulk events on the first rung that fits', () => {
    expect(paddedSize('recap', 600)).toBe(2048);
    expect(paddedSize('recap', 3000)).toBe(4096);
    expect(paddedSize('birthdays', 5000)).toBe(8192);
  });
});

describe('isEnvelope drives the anti-downgrade check', () => {
  it('recognises a real envelope', () => {
    expect(isEnvelope(fixture.cases[0].envelope)).toBe(true);
  });

  it('rejects a plaintext event body', () => {
    // This is what makes the downgrade check in useSocket possible: once a
    // screen holds a key, an unsealed payload on a name-bearing event is
    // dropped. Without it the encryption would be decorative.
    expect(isEnvelope({ firstName: 'Amy', club: 'Sparks' })).toBe(false);
    expect(isEnvelope({ entries: [], at: 'x' })).toBe(false);
  });

  it('rejects near-misses and non-objects', () => {
    for (const j of [null, undefined, 0, '', 'x', [], {},
      { v: 1, kid: 'a', iv: 'b' }, { v: 2, kid: 'a', iv: 'b', ct: 'c' }]) {
      expect(isEnvelope(j)).toBe(false);
    }
  });
});
